CAMUNDA_REST_ADDRESS=https://bru-2.zeebe.camunda.io:443/814fe23f-dae0-4a50-bdaf-7150f1bd94fa/
CAMUNDA_GRPC_ADDRESS=https://814fe23f-dae0-4a50-bdaf-7150f1bd94fa.bru-2.zeebe.camunda.io:443
# CAMUNDA_REST_ADDRESS=http://localhost:8080/
# CAMUNDA_GRPC_ADDRESS=http://localhost:26500/

CAMUNDA_TOKEN_AUDIENCE=zeebe.camunda.io
camunda.auth.server.url=https://login.cloud.camunda.io/oauth/token
# camunda.client.grpc-address=grpcs://814fe23f-dae0-4a50-bdaf-7150f1bd94fa.bru-2.zeebe.camunda.io:443
# camunda.client.rest-address=https://bru-2.zeebe.camunda.io/814fe23f-dae0-4a50-bdaf-7150f1bd94fa

camunda.client.auth.client-id=LS2UsL8M0ocSaVAUR.I2D9y2QDUotcKN
camunda.client.auth.client-secret=BRS4rrRxFZRZ3l9vQeaZlJoCGMDJFCTVRlYg~Q6MXKt8Mf.1c-p-_zkv-UfLZ8MG
camunda.client.cloud.cluster-id=814fe23f-dae0-4a50-bdaf-7150f1bd94fa
camunda.client.cloud.region=bru-2
